FROM debian:latest AS base
	LABEL author="Adastra"
	LABEL description="Simple Red Team image."
	ENV WORKDIR_ENV=/redteam/recon
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

	RUN apt-get update && apt-get -y install net-tools netcat python3 python3-dev python3-pip \
		unzip wget curl git gcc libc-dev libxslt-dev libevent-dev libssl-dev zlib1g zlib1g-dev \
		firefox-esr xfce4-terminal autoconf automake libtool apt-utils openssh-server openssl \
		build-essential libpcap-dev libpq-dev libsqlite3-dev libsqlite3-0

	RUN cd ${WORKDIR} && git clone https://github.com/lanmaster53/recon-ng.git 
	RUN cd ${WORKDIR} &&  git clone https://github.com/s0md3v/Photon 
	RUN cd ${WORKDIR} && git clone https://github.com/laramies/theHarvester 
	RUN cd ${WORKDIR} && git clone https://github.com/Mr-Un1k0d3r/MaliciousMacroGenerator