FROM debian:latest AS base
	LABEL author="Adastra"
	LABEL description="Simple Red Team image."
	ENV WORKDIR_ENV=/redteam/weaponization
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

	RUN apt-get update && apt-get -y install net-tools netcat python3 python3-dev python3-pip \
		unzip wget curl git gcc libc-dev libxslt-dev libevent-dev libssl-dev zlib1g zlib1g-dev \
		firefox-esr xfce4-terminal autoconf automake libtool apt-utils openssh-server openssl \
		build-essential libpcap-dev libpq-dev libsqlite3-dev libsqlite3-0

	RUN cd ${WORKDIR} && git clone https://github.com/WyAtu/CVE-2018-20250 CVE2018_20250
	RUN cd ${WORKDIR} && git clone https://github.com/bhdresh/CVE-2017-8759 CVE2017_8759
	RUN cd ${WORKDIR} && git clone https://github.com/rxwx/CVE-2017-8570 CVE2017_8570
	RUN cd ${WORKDIR} && git clone https://github.com/bhdresh/CVE-2017-0199 CVE2017_0199
	RUN cd ${WORKDIR} && git clone https://github.com/nccgroup/demiguise
	RUN cd ${WORKDIR} && git clone https://github.com/Mr-Un1k0d3r/MaliciousMacroGenerator
	RUN cd ${WORKDIR} && git clone https://github.com/0xdeadbeefJERKY/Office-DDE-Payloads \
			&& cd Office-DDE-Payloads && pip install -r requirements.
	RUN cd ${WORKDIR} && git clone https://github.com/Mr-Un1k0d3r/DKMC && cd DKMC \
			&& mkdir output
	RUN cd ${WORKDIR} && git clone https://github.com/Arno0x/EmbedInHTML
	RUN cd ${WORKDIR} && mkdir macro_pack && cd macro_pack && \
		wget https://github.com/sevagas/macro_pack/releases/download/v1.7/macro_pack.exe