FROM debian:latest AS base
	LABEL author="Adastra"
	LABEL description="Simple Red Team image."
	ENV WORKDIR_ENV=/redteam/anon
	WORKDIR ${WORKDIR_ENV}
	SHELL ["/bin/bash", "-c"]

	RUN apt-get update && apt-get -y install net-tools netcat python3 python3-dev python3-pip \
		unzip wget curl git gcc libc-dev libxslt-dev libevent-dev libssl-dev zlib1g zlib1g-dev \
		firefox-esr xfce4-terminal autoconf automake libtool apt-utils openssh-server openssl \
		build-essential libpcap-dev libpq-dev libsqlite3-dev libsqlite3-0

	#Install TOR from Source.
	RUN cd ${WORKDIR} && wget https://dist.torproject.org/tor-0.4.2.7.tar.gz && \
		tar -xvf tor-0.4.2.7.tar.gz && \
		rm -rf tor-0.4.2.7.tar.gz && \
		mv tor-0.4.2.7 tor-latest && \
		cd ${WORKDIR}/tor-latest && ./configure && make